In [1]:
import numpy as np

# The Basics

In [2]:
x=np.array([1,2,3],dtype='int32')
print(x)

[1 2 3]


In [4]:
y=np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(y)

[[9. 8. 7.]
 [6. 5. 4.]]


In [6]:
#GETTING ARRAY DIMENSION:
y.ndim

2

In [9]:
#GETTING SHAPE:
y.shape

(2, 3)

In [10]:
#GET TYPE
y.dtype

dtype('float64')

In [12]:
#GET SIZE:size of each int element
x.itemsize

4

In [13]:
y.itemsize

8

In [18]:
#GET TOTAL SIZE: tells us the total size of all the elements together
x.nbytes   #4* 3 elements

12

In [17]:
y.nbytes  #8* 6 elements

48

In [19]:
#GET THE NUMBER OF ELEMENTS IN AN ARRAY:
x.size

3

In [20]:
y.size

6

# Acessing/Changing specific elements,rows,columns etc

In [22]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [23]:
#GET SPECIFIC ELEMENT: (r,c)
a[1,5]

13

In [24]:
#GET A SPECIFIC ROW: including all the columns
a[1,:]

array([ 8,  9, 10, 11, 12, 13, 14])

In [25]:
#GET A SPECIFIC COLUMN: including all the rows
a[:,2]

array([ 3, 10])

In [26]:
#USING [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [30]:
a[0,1:6:2]

array([2, 4, 6])

In [29]:
#CHANGING THE ELEMENTS OF THE ARRAY:
a[1,5] = 20
a[:,2] = [1,2]
print("Array after:",a)

Array after: [[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [34]:
#3-D EXAMPLE:

In [35]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [36]:
# Get specific element (work from outside to inside in the array)
b[0,1,1]

4

In [37]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [39]:
#replace: only of the same dimensions
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


# Initializing Different Types of Arrays

In [40]:
#All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [41]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [42]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [43]:
# Any other number (full_like) in an already given list
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [47]:
np.full(a.shape,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [44]:
# Filling an array with random decimal numbers in (r,c) format
np.random.rand(4,2)

array([[0.25690921, 0.40621452],
       [0.59699296, 0.47736915],
       [0.5664923 , 0.95926615],
       [0.22714742, 0.41408806]])

In [48]:
np.random.rand(4,2,3)

array([[[0.76377896, 0.77125201, 0.00495317],
        [0.47997365, 0.14235917, 0.25496393]],

       [[0.74131213, 0.68705738, 0.54845964],
        [0.78149502, 0.64624519, 0.22436818]],

       [[0.59770694, 0.54950793, 0.69901393],
        [0.5697208 , 0.85238222, 0.65269996]],

       [[0.64072681, 0.79098572, 0.22595514],
        [0.71657551, 0.66708834, 0.46085117]]])

In [49]:
np.random.random_sample(a.shape)

array([[0.59735124, 0.69392349, 0.4268003 , 0.70623187, 0.35950082,
        0.28598505, 0.73499758],
       [0.74095543, 0.52992825, 0.79309275, 0.56745578, 0.86088105,
        0.23532855, 0.94579444]])

In [45]:
# Random Integer values with (startvalue, endvalue, size of the array)
np.random.randint(-4,8, size=(3,3))

array([[ 7,  5,  4],
       [ 4,  3,  0],
       [ 1,  2, -1]])

In [46]:
# The identity matrix with dimension given as (n)
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [51]:
# Repeat an array
arr = np.array([1,2,3])
r1 = np.repeat(arr,3)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [53]:
# With an axis specified and making the array a 2D array, to get the following result
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [54]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=1)
print(r1)

[[1 1 1 2 2 2 3 3 3]]


In [55]:
#Example:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [56]:
#Copying arrays so that the original content does not change
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(b)
print(a)

[100   2   3]
[1 2 3]


# Mathematics in NumPy

In [57]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [58]:
a + 2

array([3, 4, 5, 6])

In [64]:
a+=2
a

array([3, 4, 5, 6])

In [59]:
a - 2

array([-1,  0,  1,  2])

In [60]:
a * 2

array([2, 4, 6, 8])

In [61]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [62]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [63]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [69]:
# We can take the sin, cosin and tan of all these values:
print(np.sin(a))
print(np.cos(a))
print(np.tan(a))

[ 0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[-0.9899925  -0.65364362  0.28366219  0.96017029]
[-0.14254654  1.15782128 -3.38051501 -0.29100619]


# Linear Algebra

In [70]:
#MATRIX MULTIPLICATION:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [73]:
# DETERMINANT OF A MATRIX
c = np.identity(3)
np.linalg.det(c)

1.0

In [84]:
#INVERSE OF A MATRIX
np.linalg.inv(c)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Statistics

In [74]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [75]:
np.min(stats)

1

In [76]:
# To find the max element from both the rows:
np.max(stats, axis=1)

array([3, 6])

In [77]:
# To find the max row from both the rows:
np.max(stats, axis=0)

array([4, 5, 6])

In [78]:
# Sum:
np.sum(stats)

21

In [81]:
# Sum of each element of row1 to the corresponding element in row2 (1+4,2+5,3+6):
np.sum(stats, axis=0)

array([5, 7, 9])

In [82]:
# Sum of all the elements of row1 and sum of all the elements of row2:
np.sum(stats, axis=1)

array([ 6, 15])

# Re-Organising Arrays

In [85]:
#Re-Shaping the array:
before = np.array([[1,2,3,4],[5,6,7,8]])
print("Array before:",before)
print()

after1 = before.reshape((4,2))
print("Array after-1:",after1)
print()

after2 = before.reshape((8,1))
print("Array after-2:",after2)

Array before: [[1 2 3 4]
 [5 6 7 8]]

Array after-1: [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Array after-2: [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [86]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [87]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

# THE END